[versions]
agp = "8.5.2"
libsu = "6.0.0"
kotlin = "1.9.0"
activityCompose = "1.9.3"
composeBom = "2024.10.00"

[libraries]
libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

